-- AlterTable
ALTER TABLE "Chat" ADD COLUMN     "endY" INTEGER,
ADD COLUMN     "startY" INTEGER,
ALTER COLUMN "endX" DROP NOT NULL,
ALTER COLUMN "startX" DROP NOT NULL,
ALTER COLUMN "type" DROP NOT NULL;
